use_frameworks!

platform :ios, '8.0'

pod 'Swiftstraints', '~> 1.1.0'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.2'
pod 'XCGLogger', :git => 'https://github.com/DaveWoodCom/XCGLogger.git', :branch => 'swift_2.0'