use_frameworks!

platform :ios, '8.0'

pod 'Swiftstraints', '~> 1.1.0'
pod 'CHTCollectionViewWaterfallLayout', '~> 0.9.2'
pod 'FBSDKCoreKit', '~> 4.6.0-beta1'
pod 'FBSDKLoginKit', '~> 4.6.0-beta1'
pod 'FBSDKShareKit', '~> 4.6.0-beta1'